// Ready translated locale messages
const messages = {
  en: {
    message: {
      cloudEngineer: 'Senior Cloud Engineer',
      softwareEngineer: "Software Engineer",
      frontendEngineer: 'Front End Developer',
      hello: 'In the past, those days surrounded by routines...until entering into the programming world, everything has changed!',
      world: 'Focus on building rich interactive web apps with solid foundations of science and mathematics',
      about: 'ABOUT',
      about1: 'Offering creative design solutions to solve business problems is what I do best.',
      about2: 'I am proficient in JavaScript, CSS, HTML, and Python,' +
        'and I have expertise in utilizing frameworks like Vue.js. ' +
        'My experience encompasses scalability, performance optimization, reusability, and delivering exceptional user experiences.',
      about3: 'As a consultant and a developer, I write code that conforms to industry standards and semantic best practices.' +
        'I am able to transform static artwork into pixel prefect, interactive and fully functional interfaces.',
      exp: 'EXPERIENCE',
      assistEuropeanClientsAWSPlanning: "Assisting European clients building with AWS (EC2, Lambda, DynamoDB, S3, CloudFront).",
      implementVoiceAssistantServices: "Implementing Amazon Alexa and Google Action voice assistant services.",
      upgradeClientSideUI: "Upgrading client-side user interfaces (Vue3, Ionic 7).",
      planLocalUIIoTDevices: "Independently planning the local user interface for IoT devices using Vue.",
      buildSmartHomeCloudServices: "Building smart home cloud services, including automated trigger programs and data analysis charts.",
      useFirebaseDataManagement: "Utilizing Google Firebase for data management and extending local and cloud data interaction channels.",
      assistDesignOBankBackendTool: "Assisting in designing the OBank backend tool for billing.",
      constructOnlineAppPages: "Constructing online application pages (Horizon Securities).",
      creditCardBillingApp: "Credit card billing push notification applications (ESUN Bank, COTA Bank).",
      luffanet: "luffanet",
      fuco: 'Rawstone',
      sks: 'SKILLSET',
      edu: 'EDUCATION',
      math: 'Department of Mathematics',
      ncku: 'National Cheng Kung University',
      general: 'General Subjects',
      kshs: 'Kaohsiung Senior High School',
      myworks: 'MY WORKS',
      contact: 'CONTACT ME',
      message: 'Feel free to leave me a message',
      loading: 'Loading',
      taipei: 'Taipei',
      newtaipei: 'New Taipei',
      taoyuan: 'Taoyuan',
      finance: 'Finance',
      iot: 'IoT',
      umt: 'UMT',
      view: 'view',
      esun: 'ESUN Bank',
      cota: 'COTA Bank',
      honsec: 'Horizon Securities',
      creditCardStatement: 'Credit card statement',
      onlineOpen: 'Online account opening'
    }
  },
  zh_tw: {
    message: {
      cloudEngineer: '資深雲端工程師',
      softwareEngineer: "軟體工程師",
      frontendEngineer: '前端工程師',
      hello: '回想從前，那些重複瑣事...直到踏入程式的世界後，一切都不一樣了！',
      world: '專注於打造具豐富體驗的應用程式，憑藉科學基礎的養成與數學能力',
      about: '關於我',
      about1: '我擅長於針對商業邏輯問題提出創新的解決方案。',
      about2: '撰寫程式包括JavaScript, CSS, HTML與Python。也會靈活運用Vue這類框架。' +
        '對程式擴展性、執行效率、可重複使用性以及使用者體驗都有相關工作經驗。',
      about3: '身為一位專業的技術顧問與開發者，我能撰寫符合工業標準的程式並實踐最佳語意化，' +
        '以及將平面設計轉化成生動活潑的使用介面。',
      exp: '工作經驗',
      assistEuropeanClientsAWSPlanning: "協助歐洲客戶進行AWS規劃(EC2, Lambda, DynamoDB, S3, CloudFront)。",
      implementVoiceAssistantServices: "導入Amazon Alexa與Google Action語音助理服務。",
      upgradeClientSideUI: "客戶端使用者介面版本升級(Vue3, Ionic 7)。",
      planLocalUIIoTDevices: "獨立規劃物聯網IoT裝置本機端使用者介面，使用Vue進行開發。",
      buildSmartHomeCloudServices: "建構智慧家庭雲端服務，包括自動化觸發程式，數據分析圖表。",
      useFirebaseDataManagement: "使用Google Firebase作為資料管理，並延伸出本地端與雲端資料交互渠道。",
      assistDesignOBankBackendTool: "協助設計對帳單後台工具(OBank)。",
      constructOnlineAppPages: "建構線上申辦頁面(宏遠證券)。",
      creditCardBillingApp: "信用卡對帳單推播應用(玉山銀行、三信商銀)。",
      luffanet: "辰信資訊",
      fuco: '景承科技',
      sks: '技能組合',
      edu: '學習經驗',
      math: '數學系',
      ncku: '國立成功大學',
      general: '普通科',
      kshs: '高雄中學',
      myworks: '作品集',
      contact: '與我聯絡',
      message: '歡迎留下寶貴的訊息',
      loading: '載入中',
      taipei: '台北市',
      newtaipei: '新北市',
      taoyuan: '桃園市',
      finance: '金融業',
      iot: '物聯網',
      umt: '歐蒙德',
      view: '暸解',
      esun: '玉山銀行',
      cota: '三信商銀',
      honsec: '宏遠證券',
      creditCardStatement: '信用卡帳單',
      onlineOpen: '線上開戶'
    }
  }
};